# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-30 04:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_reg', '0003_auto_20170629_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='userName',
        ),
    ]
